// <auto-generated />
using System;
using CloudInvoice.Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudInvoice.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260909200829_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudInvoice.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Geral"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Eletrónica"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Vestuário"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Serviços"
                        });
                });

            modelBuilder.Entity("CloudInvoice.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000001"),
                            BasePrice = 45.90m,
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "P001",
                            Description = "Teclado Mecânico RGB",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000002"),
                            BasePrice = 15.50m,
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "P002",
                            Description = "Rato sem Fios",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000003"),
                            BasePrice = 129.99m,
                            CategoryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "P003",
                            Description = "Monitor 24 Polegadas",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000004"),
                            BasePrice = 8.50m,
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "P004",
                            Description = "Café em Grão 1kg",
                            IsActive = true,
                            TaxRate = 6m,
                            UnitOfMeasure = "Kg"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000005"),
                            BasePrice = 6.20m,
                            CategoryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "P005",
                            Description = "Azeite Extra Virgem 1L",
                            IsActive = true,
                            TaxRate = 6m,
                            UnitOfMeasure = "Litro"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000006"),
                            BasePrice = 12.00m,
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "P006",
                            Description = "T-shirt Algodão",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000007"),
                            BasePrice = 35.00m,
                            CategoryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Code = "P007",
                            Description = "Calças de Ganga",
                            IsActive = false,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000008"),
                            BasePrice = 45.00m,
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "P008",
                            Description = "Consultoria Informática",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Hora"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000009"),
                            BasePrice = 150.00m,
                            CategoryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Code = "P009",
                            Description = "Instalação de Rede",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Unidade"
                        },
                        new
                        {
                            Id = new Guid("a0000001-0000-0000-0000-000000000010"),
                            BasePrice = 25.00m,
                            CategoryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "P010",
                            Description = "Fita Adesiva",
                            IsActive = true,
                            TaxRate = 23m,
                            UnitOfMeasure = "Metro"
                        });
                });

            modelBuilder.Entity("CloudInvoice.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("CloudInvoice.Catalog.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CloudInvoice.Catalog.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
